/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bgbfijoxcqaiskxtngyf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYmZpam94Y3FhaXNreHRuZ3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTYwOTIsImV4cCI6MjA3MDg5MjA5Mn0.11--x5Y63MEylVEvmnEQ0OtZojWGdXicw_IUkY9zr2U"